model:
  name: unet_colorizer
  input_channels: 1
  output_channels: 2

dataset:
  name: coco_places
  path: /datasets/colorizer/
  image_size: 256

training:
  epochs: 40
  batch_size: 64

loss:
  type: "hybrid_colorization"
  l1_weight: 1.0
  perceptual_weight: 0.2
  ssim_weight: 0.1
