pipeline:
  stages:
    - colorizer
    - sr
    - depth
    - bokeh
    - tone
    - contrast
  stage_options:
    colorizer:
      color_boost: 1.35
      ab_clip: 128.0
    depth:
      inference_size: 384
    bokeh:
      kernel_size: 11
      focus_threshold: 0.2
    tone:
      iterations: 8
      channels: 32
